version: "3"
networks:
  proxy:
    external:
       name: ha-proxy
  backend:
    driver: bridge

services:
    mmbe_nginx:
        hostname: mmbe_nginx
        build:
          context: ./nginx
        image: nodejs:16.13.0-alpine-vue
        #image: registry.cn-beijing.aliyuncs.com/qiangxianfei/alpine_nginx:v1.2
        restart: always
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/sites:/etc/nginx/conf.d"
            - "./nginx/log:/var/log/nginx"
              # - "./nginx/dist:/usr/share/nginx/html"
        depends_on:
            - mmbe_app
        networks:
        - proxy
        - backend

    mmbe_app:
        hostname: mmbe_app
        restart: always
        build:
          context: ./cmdb
        depends_on:
            - mmbe_db
        networks:
        - backend    

    mmbe_db:
        hostname: mmbe_db
        image: mysql:5.7
        restart: always
        volumes:
            - "./db/mysql_conf:/etc/mysql/mysql.conf.d"
            - "./db/mysql_data:/var/lib/mysql"
            - "./db/mmbe.sql:/docker-entrypoint-initdb.d/mmbe.sql"
        environment:
            MYSQL_ROOT_PASSWORD: Flynn223..
            MYSQL_DATABASE: mmbe
            MYSQL_USER: mmbe
            MYSQL_PASSWORD: Flynn223..
            MYSQL_ROOT_HOST: "%"
        networks:
          - backend
