version: "3"
networks:
  proxy:
    external:
       name: ${PROXY_NETWORK}
  backend:
    driver: ${PROXY_NETWORK_DIRVER}

services:
    mmbe_nginx:
        hostname: ${HOSTNAME_A}
        build:
          context: ./nginx
        image: ${IMAGE_NAME_A}
        #image: registry.cn-beijing.aliyuncs.com/qiangxianfei/alpine_nginx:v1.2
        restart: always
        volumes:
            - ${NGINX_CONF}:/etc/nginx/nginx.conf
            - ${NGINX_SITES}:/etc/nginx/conf.d
            - ${NGINX_LOG_DIR}:/var/log/nginx
              # - "./nginx/dist:/usr/share/nginx/html"
        depends_on:
            - mmbe_app
        networks:
        - proxy
        - backend

    mmbe_app:
        hostname: ${HOSTNAME_B}
        restart: always
        build:
          context: ./cmdb
        depends_on:
            - mmbe_db
        networks:
        - backend    

    mmbe_db:
        hostname: ${HOSTNAME_C}
        image: ${IMAGE_NAME_C}
        restart: always
        volumes:
            - ${DB_CONF_DIR}:/etc/mysql/mysql.conf.d
            - ${DB_DATA_DIR}:/var/lib/mysql
            - ${SOURCE_SQL_FILE}:/docker-entrypoint-initdb.d/mmbe.sql
        environment:
            MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
            MYSQL_DATABASE: DATABASE_NAME
            MYSQL_USER: USER
            MYSQL_PASSWORD: USER_PASSWORD
            MYSQL_ROOT_HOST: "%"
        networks:
          - backend
