version: "3"
networks:
  default:
    external:
      name: ha-proxy

services:
    nginx-proxy:
        hostname: nginx_proxy
        image: registry.cn-beijing.aliyuncs.com/qiangxianfei/alpine_nginx:v1.2
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./ssl:/etc/nginx/cert"
            - "./sites:/etc/nginx/conf.d"
            - "./log:/var/log/nginx"
